// F15.2: a clip of a real talk with subtitles generated by Everyone Makes Subs.
// Cuts the clip (YouTube or a local video), runs the real pipeline over its audio (Live API →
// segmenter → translator), exports the VTT in the chosen language and burns it into the video.
//
// Usage:
//   npx tsx scripts/subtitle-clip.ts <youtube-url|video-file> --from=03:00 --to=04:30 [--lang=en] [--src-lang=es]
//        [--title="…"] [--speaker="…"] [--out=demo/clip] [--vtt=existing.vtt]
//   Output: <out>.mp4 (the cut), <out>.<lang>.vtt, <out>.<lang>.mp4 (burned-in subtitles), plus .srt/.txt.
//   --vtt skips the pipeline and only burns an existing VTT (no key needed).
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import ffmpegPath from 'ffmpeg-static';
import { generateGlossary } from '../server/src/ai/auxModel.js';
import { findYtDlp, ORIGINAL_AUDIO } from '../server/src/audio/ytdlp.js';
import { loadConfig } from '../server/src/config.js';
import { runFile } from '../server/src/stage/runFile.js';
import { toSrt, toTxt, toVtt } from '../server/src/store/export.js';

try { process.loadEnvFile(); } catch { /* no .env */ }
const cfg = loadConfig();
const args = process.argv.slice(2);
const input = args.find((a) => !a.startsWith('--'));
const opt = (n: string) => args.find((a) => a.startsWith(`--${n}=`))?.split('=').slice(1).join('=');
if (!input) { console.log('Usage: npx tsx scripts/subtitle-clip.ts <youtube-url|video> --from=03:00 --to=04:30 --lang=en'); process.exit(2); }

const secs = (s?: string) => (s ? s.split(':').reduce((acc, p) => acc * 60 + Number(p), 0) : 0);
const from = secs(opt('from'));
const to = secs(opt('to'));
const lang = opt('lang') ?? 'en';
const srcLang = opt('src-lang') ?? 'es';
const out = opt('out') ?? 'demo/clip';
fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });

function ff(argv: string[], cwd?: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn(ffmpegPath as unknown as string, ['-hide_banner', '-loglevel', 'error', '-y', ...argv], { cwd, stdio: ['ignore', 'inherit', 'inherit'] });
    p.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`ffmpeg exited with ${code}`))));
  });
}

async function run(bin: string, argv: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const p = spawn(bin, argv, { stdio: ['ignore', 'pipe', 'inherit'] });
    let outText = '';
    p.stdout.on('data', (d: Buffer) => { outText += d.toString(); });
    p.on('exit', (code) => (code === 0 ? resolve(outText.trim()) : reject(new Error(`${bin} exited with ${code}`))));
  });
}

// 1. the clip
const clip = `${out}.mp4`;
const range = to > from ? ['-ss', String(from), '-t', String(to - from)] : [];
if (/^https?:\/\//.test(input)) {
  const ytdlp = await findYtDlp(cfg.dataDir);
  // YouTube serves video and audio apart: ≤720p video + the ORIGINAL audio track (not an AI dub)
  const video = (await run(ytdlp, ['--no-warnings', '-f', 'bv*[height<=720][ext=mp4]/bv*[height<=720]/bv*', '-g', input])).split(/\r?\n/)[0];
  const audio = (await run(ytdlp, ['--no-warnings', '-f', ORIGINAL_AUDIO, '-g', input])).split(/\r?\n/)[0];
  console.log(`[clip] cutting ${opt('from') ?? '0'}–${opt('to') ?? 'end'} from YouTube`);
  const seek = range.slice(0, 2);
  await ff([...seek, '-i', video, ...seek, '-i', audio, ...range.slice(2), '-map', '0:v:0', '-map', '1:a:0',
    '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '22', '-c:a', 'aac', '-b:a', '128k', clip]);
} else {
  console.log(`[clip] cutting ${input}`);
  await ff([...range.slice(0, 2), '-i', input, ...range.slice(2), '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '22', '-c:a', 'aac', '-b:a', '128k', clip]);
}

// 2. subtitles from the real pipeline (or an existing VTT)
const vtt = `${out}.${lang}.vtt`;
if (opt('vtt')) {
  fs.copyFileSync(opt('vtt')!, vtt);
} else {
  if (!cfg.geminiApiKey) { console.log('No Gemini key: put GEMINI_API_KEY in .env (or pass --vtt=file to only burn).'); process.exit(2); }
  const talk = { title: opt('title') ?? path.basename(out), speaker: opt('speaker'), lang: srcLang };
  const glossary = await generateGlossary(cfg, talk);
  console.log(`[clip] vocabulary: ${glossary.asrVocabulary.slice(0, 15).join(', ')}`);
  console.log(`[clip] running the pipeline in real time over ${Math.round(to - from) || '?'} s of audio…`);
  const r = await runFile({ cfg, file: clip, label: 'clip', targetLangs: [...new Set([srcLang, lang])], talk: { ...talk, glossary } });
  fs.writeFileSync(vtt, toVtt(r.segments, lang === srcLang ? undefined : lang));
  fs.writeFileSync(`${out}.${lang}.srt`, toSrt(r.segments, lang === srcLang ? undefined : lang));
  fs.writeFileSync(`${out}.${lang}.txt`, toTxt(r.segments, lang === srcLang ? undefined : lang, talk.title));
  console.log(`[clip] ${r.segments.length} segments · translation p50 ${[...r.mtMs].sort((a, b) => a - b)[Math.floor(r.mtMs.length / 2)] ?? '?'} ms`);
}

// 3. burn in (run from the output folder so the subtitles filter gets a path without a drive colon)
const dir = path.dirname(path.resolve(clip));
const style = "FontName=Arial,FontSize=20,PrimaryColour=&H00FFFFFF,OutlineColour=&H80000000,BorderStyle=3,Outline=1,Shadow=0,MarginV=28";
await ff(['-i', path.basename(clip), '-vf', `subtitles=${path.basename(vtt)}:force_style='${style}'`, '-c:a', 'copy', `${path.basename(out)}.${lang}.mp4`], dir);
console.log(`[clip] done: ${out}.${lang}.mp4 (subtitles: ${vtt})`);
