// UI strings for the attendee-facing surfaces (phone, TV, overlay). Operator UI (station,
// dashboard, setup) stays in English per .claude/rules/frontend.md.

export type Lang = 'es' | 'en' | 'pt';
export const SUPPORTED_LANGS: Lang[] = ['es', 'en', 'pt'];

export function isLang(v: string | null | undefined): v is Lang {
  return v === 'es' || v === 'en' || v === 'pt';
}

/** `?lang=` wins; otherwise the first matching `navigator.language` prefix; otherwise `fallback`. */
export function detectLang(queryLang: string | null, fallback: Lang = 'en'): Lang {
  if (isLang(queryLang)) return queryLang;
  const nav = typeof navigator !== 'undefined' ? navigator.language.slice(0, 2).toLowerCase() : '';
  if (isLang(nav)) return nav;
  return fallback;
}

export interface LangMeta {
  name: string; // the language's own name, e.g. "English"
  sound: string; // "applause" chip word
  speaking: string; // "speaking…" word while a phrase is mid-translation
}

export const LANG_META: Record<Lang, LangMeta> = {
  es: { name: 'Español', sound: 'aplausos', speaking: 'hablando' },
  en: { name: 'English', sound: 'applause', speaking: 'speaking' },
  pt: { name: 'Português', sound: 'aplausos', speaking: 'falando' },
};

/** "original" / "translation" label, relative to the talk's own language. */
export function subLabel(lang: Lang, isOriginal: boolean): string {
  if (isOriginal) return lang === 'es' ? 'original' : lang === 'pt' ? 'idioma original' : 'original';
  return lang === 'es' ? 'traducción' : lang === 'pt' ? 'tradução' : 'translation';
}

interface Strings {
  live: string; paused: string; noAudio: string; break: string; ended: string; reconnecting: string;
  pausedTitle: string;
  noSignalTitle: string; noSignalBody: string;
  breakTitle: (time: string) => string; breakBody: (title: string, speaker: string) => string;
  endedTitle: string; endedBody: string;
  downloadTxt: string; downloadSrt: string; seeSummary: string;
  reconnectingBanner: string;
  langToast: (name: string) => string; langToastChange: string;
  langSheetTitle: string; langSheetHelp: (talkLang: string) => string;
  aaSheetTitle: string; textSize: string; showOriginalBelow: string; showOriginalBelowHint: string;
  showLiveOriginal: string; showLiveOriginalHint: string; watchingStream: string; watchingStreamHint: string;
  delay: string; keepScreenOn: string;
  jumpToLive: string;
  whatDidIMiss: string;
  summaryTitle: string; summaryHelp: string; summaryClose: string; summaryEmpty: string;
  translating: string;
}

export const STRINGS: Record<Lang, Strings> = {
  en: {
    live: 'live', paused: 'live', noAudio: 'no audio', break: 'break', ended: 'ended', reconnecting: 'live',
    pausedTitle: 'The speaker paused',
    noSignalTitle: 'Waiting for audio from the room', noSignalBody: 'Captions will come back on their own.',
    breakTitle: (time) => `Break · back at ${time}`,
    breakBody: (title, speaker) => `Next: "${title}"${speaker ? `, ${speaker}` : ''}.`,
    endedTitle: 'The talk has ended', endedBody: 'Take the full transcript with you.',
    downloadTxt: 'Download text', downloadSrt: '.srt', seeSummary: 'See summary',
    reconnectingBanner: "Reconnecting… when we're back, we'll show you what you missed.",
    langToast: (name) => `Showing ${name}, your phone's language.`, langToastChange: 'Change',
    langSheetTitle: 'Caption language',
    langSheetHelp: (talkLang) => `The talk is in ${talkLang}. Translations arrive 1–2 seconds after the original.`,
    aaSheetTitle: 'Reading settings', textSize: 'Text size',
    showOriginalBelow: 'Show the original below', showOriginalBelowHint: "Useful if you understand some of the talk's language",
    showLiveOriginal: 'Show the original while translating', showLiveOriginalHint: 'A small gray line so you can tell where the speaker is',
    watchingStream: "I'm watching the stream", watchingStreamHint: 'Delays captions to match the video',
    delay: 'Delay', keepScreenOn: 'Keep the screen on',
    jumpToLive: '↓ Back to live',
    whatDidIMiss: 'What did I miss?',
    summaryTitle: 'The last 5 minutes', summaryHelp: 'Updated every minute. Generated by Gemini from the transcript.',
    summaryClose: 'Back to captions', summaryEmpty: 'Not enough captions yet.',
    translating: 'translating…',
  },
  es: {
    live: 'en vivo', paused: 'en vivo', noAudio: 'sin audio', break: 'intervalo', ended: 'finalizada', reconnecting: 'en vivo',
    pausedTitle: 'El orador hizo una pausa',
    noSignalTitle: 'Esperando sonido de la sala', noSignalBody: 'Los subtítulos vuelven solos. No tenés que hacer nada.',
    breakTitle: (time) => `Intervalo · volvemos ${time}`,
    breakBody: (title, speaker) => `Próxima: «${title}»${speaker ? `, ${speaker}` : ''}.`,
    endedTitle: 'La charla terminó', endedBody: 'Podés llevarte la transcripción completa.',
    downloadTxt: 'Descargar texto', downloadSrt: '.srt', seeSummary: 'Ver resumen',
    reconnectingBanner: 'Reconectando… cuando volvamos, te mostramos lo que te perdiste.',
    langToast: (name) => `Mostrando ${name}, el idioma de tu teléfono.`, langToastChange: 'Cambiar',
    langSheetTitle: 'Idioma de los subtítulos',
    langSheetHelp: (talkLang) => `La charla es en ${talkLang}. Las traducciones llegan 1-2 segundos después del original.`,
    aaSheetTitle: 'Ajustes de lectura', textSize: 'Tamaño del texto',
    showOriginalBelow: 'Mostrar el original debajo', showOriginalBelowHint: 'Útil si entendés algo del idioma de la charla',
    showLiveOriginal: 'Mostrar el original mientras se traduce', showLiveOriginalHint: 'Una línea gris para saber por dónde va el orador',
    watchingStream: 'Estoy mirando el stream', watchingStreamHint: 'Retrasa los subtítulos para que coincidan con el video',
    delay: 'Retraso', keepScreenOn: 'Mantener la pantalla encendida',
    jumpToLive: '↓ Volver al vivo',
    whatDidIMiss: '¿Qué me perdí?',
    summaryTitle: 'Los últimos 5 minutos', summaryHelp: 'Se actualiza cada minuto. Lo arma Gemini a partir de la transcripción.',
    summaryClose: 'Volver a los subtítulos', summaryEmpty: 'Todavía no hay suficientes subtítulos.',
    translating: 'traduciendo…',
  },
  pt: {
    live: 'ao vivo', paused: 'ao vivo', noAudio: 'sem áudio', break: 'intervalo', ended: 'encerrada', reconnecting: 'ao vivo',
    pausedTitle: 'O palestrante fez uma pausa',
    noSignalTitle: 'Aguardando o áudio da sala', noSignalBody: 'As legendas voltam sozinhas.',
    breakTitle: (time) => `Intervalo · voltamos ${time}`,
    breakBody: (title, speaker) => `Próxima: «${title}»${speaker ? `, ${speaker}` : ''}.`,
    endedTitle: 'A palestra terminou', endedBody: 'Leve a transcrição completa.',
    downloadTxt: 'Baixar texto', downloadSrt: '.srt', seeSummary: 'Ver resumo',
    reconnectingBanner: 'Reconectando… quando voltarmos, mostramos o que você perdeu.',
    langToast: (name) => `Mostrando ${name}, o idioma do seu telefone.`, langToastChange: 'Mudar',
    langSheetTitle: 'Idioma das legendas',
    langSheetHelp: (talkLang) => `A palestra é em ${talkLang}. As traduções chegam 1-2 segundos depois do original.`,
    aaSheetTitle: 'Ajustes de leitura', textSize: 'Tamanho do texto',
    showOriginalBelow: 'Mostrar o original abaixo', showOriginalBelowHint: 'Útil se você entende algo do idioma da palestra',
    showLiveOriginal: 'Mostrar o original enquanto traduz', showLiveOriginalHint: 'Uma linha cinza para saber onde o palestrante está',
    watchingStream: 'Estou assistindo à transmissão', watchingStreamHint: 'Atrasa as legendas para bater com o vídeo',
    delay: 'Atraso', keepScreenOn: 'Manter a tela ligada',
    jumpToLive: '↓ Voltar ao vivo',
    whatDidIMiss: 'O que eu perdi?',
    summaryTitle: 'Os últimos 5 minutos', summaryHelp: 'Atualizado a cada minuto. Gerado pelo Gemini a partir da transcrição.',
    summaryClose: 'Voltar às legendas', summaryEmpty: 'Ainda não há legendas suficientes.',
    translating: 'traduzindo…',
  },
};

/** Tail of `t` cut at a word boundary, at most `n` characters (used by TV/overlay caption budgets). */
export function tail(t: string, n: number): string {
  if (t.length <= n) return t;
  const cut = t.slice(t.length - n);
  const i = cut.indexOf(' ');
  return '…' + (i >= 0 ? cut.slice(i + 1) : cut);
}
